spring:
  application:
    name: amira-service
  sleuth:
    sampler:
      percentage: 0.5
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: 
          - "*"
#server:
#  port: 8081
#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
