security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8080/user
spring:
  cloud:
    stream:
      bindings:
        output:
          destination: elit
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: amira-service
  sleuth:
    sampler:
      percentage: 0.5
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: 
          - "*"
#server:
#  port: 1808
#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#amira-service:
  #ribbon:
    #eureka:
      #enabled: true
