spring:
  application:
    name: api-gateway
  cloud:
    config:
      uri: 
        - http://localhost:9000
        
zuul:
  prefix: /api
  routes:
    user-service:
      path: /user-service/**
      service-id: user-service
    task-service:
      path: /task-service/**
      service-id: task-service
    test1-service:
      path: /task/**
      service-id: test1-service
    test2-service:
      path: /user/**
      service-id: test2-service



#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka 
    
    
    
