spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: 360gunner
    password: 1998
  application:
    name: api-gateway
  cloud:
    config:
      uri: 
        - http://localhost:9000
  sleuth:
    sampler:
      percentage: 0.5        
zuul:
  routes:
    user-service:
      path: /user-service/**
      service-id: user-service
    houssem-service:
      path: /houhou/**
      service-id: houssem-service
    task-service:
      path: /task-service/**
      service-id: task-service
    test1-service:
      path: /task/**
      service-id: test1-service
    test2-service:
      path: /user/**
      service-id: test2-service
    amira-service:
      path: /mira/**
      service-id: amira-service
  #prefix: /api
#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka 
    
    
    
