spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        input:
          destination: elit
  application:
    name: houssem-service
  sleuth:
    sampler:
      percentage: 0.5
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: 
          - "*"
#server:
#  port: 1808
#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
amira-service:
  ribbon:
    eureka:
      enabled: true
