security:
  oauth2:
    client:
      clientId: houssem
      clientSecret: amira
      authorized-grant-types: authorization_code,refresh_token,password,client_credentials
      scope: amira,houssem
zuul:
  routes:
    houssem-service:
      path: /houhou/**
      service-id: houssem-service
    amira-service:
      path: /mira/**
      service-id: amira-service
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: 360gunner
    password: 1998
  sleuth:
    sampler:
      percentage: 0.5
  application:
    name: secured-gateway
  cloud:
    config:
      uri: 
        - http://localhost:9000
  datasource:
    password: root
    testWhileIdle: true
    url: jdbc:mysql://localhost:3306/springtest?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
        
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka 
