spring:
  application:
    name: task-service
 
    
 
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: 
          - "*"
#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8083

application:
  version: task-service-v4
