spring:
  application:
    name: test1-service
    

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: 
          - "*"
server:
  port: 8087
#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  


