spring:
  application:
    name: test2-service
    
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: 
          - "*"
server:
  port: 8091
#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  


